spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamerental
    username: johndoe
    password: somew0rds

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug